title: Nap
description: A privacy-focused sleep tracking app
theme: minima

# GitHub Pages settings
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Navigation
header_pages:
  - index.md
  - PrivacyPolicy.md
  - TermsOfService.md

# Site settings
email: nslandteam@gmail.com
github_username: your-github-username

# Build settings
markdown: kramdown
highlighter: rouge 